<?php

?>

<style>
    .btn-outline-danger,
    .btn-outline-primary {
        width: 20%;
        /*border-radius: 16px;*/
    }

    /*
    .content-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        border-radius: 5px 5px 0 0;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

    .content-table thead tr {
        background-color: #0c5460;
        color: white;
        text-align: left;
        font-weight: bold;
    }

    .content-table th,
    .content-table td {
        padding: 12px 15px;
    }

    .content-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .content-table tbody tr: nth-of-type(even) {
        background-color: #0c5460;
    }

    .content-table tbody tr:last-of-type {
        border-bottom: 2px solid #0c5460;
    }*/

    .first-column {
        font-weight: bold;
    }

    .table th,
    .table td {
        padding: 10px 15px;
        text-align: left;
    }

    .table th:last-of-type,
    .table td:last-of-type {
        text-align: right;
    }

    .table tbody tr:last-of-type {
        border-bottom: 2px solid gray;
    }

    .table thead th{
        border-top: 2px solid gray;
        border-bottom: 2px solid gray;
    }

    .table {
        margin: 25px 0;
        border-radius: 5px 5px 0 0;
        overflow: hidden;
    }

    #add-button {
        margin-top: 20px;
    }

</style>


<div class="container-fluid">

    <div class="row">
        <h3>Lista de pessoas</h3>
    </div>

    <div class="row">
        <div class="col-md-12">

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th></th>
                </tr>
                </thead>

                <?php
                foreach ($persons

                         as $person) :
                    ?>

                    <tr>
                        <td class="first-column"><?= $person->getId() ?></td>
                        <td><?= $person->getName() ?></td>
                        <td><?= $person->getSurname() ?></td>
                        <td class="button-column">
                            <a href="<?= $this->url('person', ['action' => 'edit', 'id' => $person->getId()]) ?>"
                               class="btn btn-outline-primary btn-sm">editar</a>
                            <a href="<?= $this->url('person', ['action' => 'remove', 'id' => $person->getId()]) ?>"
                               class="btn btn-outline-danger btn-sm">remover</a>
                        </td>
                    </tr>


                <?php
                endforeach;
                ?>

            </table>
        </div>

    </div>


    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <a href="<?= $this->url('person', ['action' => 'add']) ?>"
               class="btn btn-primary btn-block" id="add-button">Adicionar</a>
        </div>
        <div class="col-md-4">
        </div>
    </div>

</div>

